# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x11\n\x0fMessageWithUuid\"\x1f\n\x0bGetResponse\x12\x10\n\x08messages\x18\x01 \x01(\t\",\n\x0bPostRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\x04\x42\x61se\x12+\n\x03get\x12\x16.google.protobuf.Empty\x1a\x0c.GetResponse\x12,\n\x04post\x12\x0c.PostRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEWITHUUID._serialized_start=48
  _MESSAGEWITHUUID._serialized_end=65
  _GETRESPONSE._serialized_start=67
  _GETRESPONSE._serialized_end=98
  _POSTREQUEST._serialized_start=100
  _POSTREQUEST._serialized_end=144
  _BASE._serialized_start=146
  _BASE._serialized_end=243
# @@protoc_insertion_point(module_scope)
